### ISSUE TITLE
MovieHub. Статистка по фильмам. Некорректная отображение посещенных страниц.

### ISSUE THREAD

**Issue by AlfaIV** [AlfaIV/homework-1-spring-2024#10]
__Приоритет:__ низский

__URL:__ [https://movie-hub.ru/userStatistic](https://movie-hub.ru/userStatistic)
__Как воспроизвести:__

1. Авторизоваться.
2. Перейти на[страницу каталога всех фильмов
](https://movie-hub.ru/films/?title=&date_from=&date_to=&rating_from=&rating_to=&mpaa=&genre=&actors=).
3. Посетить страницу нескольких фильмов. Запомнить порядок посещения страниц фильмов.
4. Перейти на [страницу Статистика](https://movie-hub.ru/userStatistic).

__Ожидаемый результат:__пункт “Последнии фильмы” отображает посещенные страницы фильмов слево-направо
__Фактический результат:__ пункт “Последнии фильмы” отображает посещенные страницы фильмов справа-налево

**Comment by Gokert** [comment]
Апрув

**Comment by AlfaIV** [comment]
Апрув

**Comment by JuFnd** [comment]
Аппрув

**Comment by BeeHeather** [comment]
* Приоритет - **низкий**
* Пункт - «**Последние** фильмы»
* В пункте 3 лучше указать конкретное количество страниц фильмов, которые необходимо открыть для воспроизведения бага. И нужно ли после посещения страницы фильма возвращаться в каталог? Если да, добавьте соответствующий пункт в шаги
* В названии конкретизируйте, что значит «Некорректное отображение»

**Comment by JuFnd** [comment]
не баг
