### ISSUE TITLE
MovieHub. Страница регистрации. Невалидная кириллица в email.

### ISSUE THREAD

**Issue by AlfaIV** [AlfaIV/homework-1-spring-2024#11]
__Приоритет:__ низкий

__Как воспроизвести:__

1. Перейти [на форму регистрации на сайте](https://movie-hub.ru/registration)
2. Заполнить форму регистрации.

![image](https://github.com/AlfaIV/homework-1-spring-2024/assets/69037858/72ee606e-9f59-46df-a7c3-c24ef88d6f13)

__Фактический результат:__ При заполнении кириллицей появляется ошибка (хотя есть адреса и домены с кириллическими символами)

**Comment by Gokert** [comment]
Апрув

**Comment by AlfaIV** [comment]
Апрув

**Comment by JuFnd** [comment]
Аппрув

**Comment by BeeHeather** [comment]
Это не дубль бага? https://github.com/AlfaIV/homework-1-spring-2024/issues/8
